server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tdb_todo_service222
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
